name: 'Render Quarto project'
author: 'Carlos Scheidegger'
description: 'This action will render an existing quarto project'
inputs:
  to:
    description: 'Service to publish to. If unspecified, use the default value derived from _publish.yml'
    required: false
  CONNECT_SERVER:
    description: 'RStudio Connect server. If unspecified, use the default value derived from _publish.yml'
    required: false
  CONNECT_API_KEY:
    description: 'RStudio Connect API key. (Use with github actions secrets: see documentation and examples for details)'
    required: false
  NETLIFY_AUTH_TOKEN:
    description: 'Netlify Auth Token. (Use with github actions secrets: see documentation and examples for details)'
    required: false
  GITHUB_EMAIL:
    description: 'Email to be used on gh-pages commit'
    required: false
    default: quarto-github-actions-publish@example.com
  GITHUB_USERNAME:
    description: 'User name to be used on gh-pages commit'
    required: false
    default: Quarto GHA Workflow Runner
runs:
  using: 'composite'
  steps: 
    - name: 'Publish'
      shell: bash
      env:
        CONNECT_SERVER: ${{ inputs.CONNECT_SERVER }}
        CONNECT_API_KEY: ${{ inputs.CONNECT_API_KEY }}
        NETLIFY_AUTH_TOKEN: ${{ inputs.NETLIFY_AUTH_TOKEN }}
      run: |
        git config --global user.email "${{ inputs.GITHUB_EMAIL }}"
        git config --global user.name "${{ inputs.GITHUB_USERNAME }}"
        quarto publish ${{ inputs.to }}
