name: 'Render Quarto project'
author: 'Carlos Scheidegger'
description: 'This action will render an existing quarto project'
inputs:
  to:
    description: 'Service to publish to. If unspecified, use the default value derived from _publish.yml'
    required: false
  CONNECT_SERVER:
    description: 'RStudio Connect server. If unspecified, use the default value derived from _publish.yml'
    required: false
  CONNECT_API_KEY:
    description: 'RStudio Connect API key. (Use with github actions secrets: see documentation and examples for details)'
    required: false
  NETLIFY_AUTH_TOKEN:
    description: 'Netlify Auth Token. (Use with github actions secrets: see documentation and examples for details)'
    required: false
  #GITHUB_TOKEN:
  #  description: 'Github Auth Token. (Use with github actions secrets: see documentation and examples for details)'
  #  required: false
runs:
  using: 'composite'
  steps: 
    - name: 'Publish'
      shell: bash
      env:
        CONNECT_SERVER: ${{ inputs.CONNECT_SERVER }}
        CONNECT_API_KEY: ${{ inputs.CONNECT_API_KEY }}
        NETLIFY_AUTH_TOKEN: ${{ inputs.NETLIFY_AUTH_TOKEN }}
        #GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: quarto publish ${{ inputs.to }}
