name: 'Render Quarto project'
author: 'Carlos Scheidegger'
description: 'This action will render an existing quarto project'
inputs:
  to:
    description: 'Service to publish to. If unspecified, use the default value derived from _publish.yml'
    required: false
runs:
  using: 'composite'
  steps: 
    - name: 'Publish'
      shell: bash
      env:
        CONNECT_SERVER: ${{ inputs.CONNECT_SERVER }}
        CONNECT_API_KEY: ${{ inputs.CONNECT_API_KEY }}
        NETLIFY_AUTH_TOKEN: ${{ inputs.NETLIFY_AUTH_TOKEN }}
      run: quarto publish ${{ inputs.to }}
#      quarto publish netlify
#      shell: bash
#    - name: 'Publish to RStudio Connect'
#      if: ${{ inputs.to == "connect" }}
#      run: |
#        quarto publish netlify --no-prompt
#      shell: bash
#    - name: 'Publish to github pages'
#      if: ${{ inputs.to == "gh-pages" }}
#      run: |
#        
#      shell: bash
    

    # https://rsc.radixu.com/ RSC server <-----

    # https://dev.to/github/the-githubtoken-in-github-actions-how-it-works-change-permissions-customizations-3cgp gh-pages

    # XU7RBaftHOyu1YLFuXfa1aDyafEzMYTv